version: "3.9"

services:
  rstudio:
    build: .
    container_name: mexclim-rstudio
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: "true"
    volumes:
      - ./Data:/home/rstudio/project/Data
      - ./Results:/home/rstudio/project/Results

  batch:
    build: .
    volumes:
      - ./Data:/home/rstudio/project/Data
      - ./Results:/home/rstudio/project/Results
    command: Rscript MAIN.R    